### ISSUE TITLE
Losing KeyIn/KeyOut type parameters when using directories

### ISSUE THREAD

**Issue by NuckChorris** [josephg/node-foundationdb#70] opened 2023-04-09 09:10 UTC
Whenever I use `.at` with a directory, it loses my key/value encoders, see following including the types reported in VS Code:

```typescript
import fdb from 'foundationdb';

fdb.setAPIVersion(620);

const rootDb = fdb.open().withKeyEncoding(fdb.tuple);

const directorySubspace = rootDb.at(await fdb.directory.createOrOpen(rootDb, 'test'));
// const directorySubspace: fdb.Database<NativeValue, Buffer, NativeValue, Buffer>

const stringSubspace = rootDb.at('test');
// const stringSubspace: fdb.Database<string | number | boolean | Buffer | BigInt | TupleArr | {
//     type: "uuid";
//     value: Buffer;
// } | {
//     type: "float";
//     value: number;
//     rawEncoding?: Buffer | undefined;
// } | ... 5 more ... | undefined, fdb.TupleItem[], NativeValue, Buffer>
```

As you can see, it works fine if my subspace is a string prefix, but a directory prefix seems to break the type and lose my key/value encoders :(

**Comment by NuckChorris** [comment] 2023-04-10 02:53
Actually these types may be accurate, it seems like `.at` resets the encoders, which seems... odd? Is this behavior intentional?

**Comment by josephg** [comment] 2023-04-17 04:00
Yes, it is odd - and its certainly not ideal. When I wrote it I wasn't sure what the behaviour should be in this case, and the directory layer code is mostly ported directly from the python bindings to keep things simple. I'm having a re-read of the code to see how it could be improved. It seems like a pretty obvious fix to plumb the KV transformers through.

The problem is when you call `DirectoryLayer#createOrOpen` like this:

```typescript
fdb.directory.createOrOpen(rootDb, 'test')
```

It doesn't inherit the KV transformers from the passed database.

The relevant code is [here](https://github.com/josephg/node-foundationdb/blob/6c5054f616d1a0586e677771190ef811e5e56990/lib/directory.ts#L556-L560). If you follow that down, [contentSubspaceForNode](https://github.com/josephg/node-foundationdb/blob/6c5054f616d1a0586e677771190ef811e5e56990/lib/directory.ts#L842-L844) should take an optional subspace and then we can plumb your `rootDb` through.

You're welcome to put together a PR. We'll have to bump the major version number because it'll be a semver-breaking change.

**Comment by josephg** [comment] 2023-04-17 04:49
... I've thrown together the [first pass of a fix for this](https://github.com/josephg/node-foundationdb/commit/acacb303d95e15646006621c88bdbf3deed52411). I don't like the template parameters everywhere, but I think its the right solution. Bleh.

**Comment by josephg** [comment] 2023-04-17 08:30
... And I published it as `foundationdb@2`. Give it a try and let me know if there are any problems. Windows support has been removed for now due to [this issue](https://forums.foundationdb.org/t/fdb-c-types-h-missing-in-windows-install-image/3817).

**Closed** 2023-04-23 23:45 UTC
